name: Build
run-name: Build
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device: ["tanmatsu"]
    steps:
      - run: sudo apt-get install git wget flex bison gperf python3 python3-pip python3-venv cmake ninja-build ccache libffi-dev libssl-dev dfu-util libusb-1.0-0
      - name: Check out repository
        uses: actions/checkout@v4
      - run: make prepare
      - run: make build DEVICE=${{ matrix.device }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.device }}
          path: |
            build/${{ matrix.device }}/application.bin
            build/${{ matrix.device }}/application.elf
